### ISSUE TITLE
Clearlinux Packages - FreeCAD 

### ISSUE THREAD

**Issue by luzpaz** [luzpaz/FreeCAD-dependencies#39]
https://github.com/clearlinux-pkgs/FreeCAD

CC @fenrus75

The spec description for FreeCAD is missing or incorrect (see https://github.com/clearlinux-pkgs/FreeCAD/blob/master/FreeCAD.spec#L10) 

Here is how other packages describe FreeCAD: https://repology.org/metapackage/freecad/packages

**Comment by fenrus75** [comment]
our autopackaging tooling just takes a paragraph or two from the readme and similar files, but in this case it took it from a pkg-info file seveveral directories deep. I've adjusted the tooling heuristics to prefer files from the main dir

(but description and co are not end user visible in clear linux, they are used nowhere)

**Comment by luzpaz** [comment]
Thank you very much for addressing this. :thumbsup:
